# docker run --name gympass-api -e POSTGRESQL_USERNAME=gympass -e POSTGRESQL_PASSWORD=gympass -e POSTGRESQL_DATABASE=gympass bitnami/postgresql:latest

# VERSAO DO DOCKER-COMPOSE
version: '3'

services:
  gympass-api:
    image: bitnami/postgresql
    ports:
      - 3332:3332
    environment:
      - POSTGRESQL_USERNAME=gympass-api
      - POSTGRESQL_PASSWORD=gympass
      - POSTGRESQL_DATABASE=gympass